### ISSUE TITLE
FR: Add GOOS build arg to Dockerfile

### ISSUE THREAD

**Issue by eddiezane** [google/triage-party#212]
The current Dockerfile assumes that you are building the image on the same OS/Arch that you are running it.

In my case I am building the image on macOS and deploying to Linux.

**Comment by tstromberg** [comment]
@eddiezane - PR's welcome!

I'm no Docker expert, but AFAIK, building a Dockerfile assumes Linux, as it is the only platform which natively supports Docker.

**Comment by eddiezane** [comment]
Safe to close - turned out to be a mistake with my configuration.
