### ISSUE TITLE
kanban:  can't evaluate field GetClosedIssues in type *provider.Milestone 

### ISSUE THREAD

**Issue by tstromberg** [google/triage-party#228]
milestone-based kanban pages at HEAD now emit the following error:

`23 open issues, collection page for "milestone": template: kanban.tmpl:82:90: executing "content" at <.Milestone.GetClosedIssues>: can't evaluate field GetClosedIssues in type *provider.Milestone `

You can see it here:

https://teaparty-tts3vkcpgq-uc.a.run.app/k/milestone

I believe this may be a regression from #193

**Comment by RCheesley** [comment]
Confirmed this bug with our instance also!
