### ISSUE TITLE
Issue filters aren't being applied correctly

### ISSUE THREAD

**Issue by gsquared94** [google/triage-party#229]
For the Skaffold project:
![image](https://user-images.githubusercontent.com/39389231/96226731-b3cab880-0fb0-11eb-93ec-b9407ef139a1.png)
6 days, 14 days, 4 weeks and 4 weeks are all less than the 6 week threshold for this filter.

**Comment by briandealwis** [comment]
Seeing this again:

![Screen Shot 2020-12-17 at 4 57 35 PM](https://user-images.githubusercontent.com/202851/102548724-11e74b00-4089-11eb-89e2-25e24d554031.png)
