### ISSUE TITLE
Documentation: clarify token file

### ISSUE THREAD

**Issue by RCheesley** [google/triage-party#37]
Hi there,

Looking to try this out with the Mautic community, however I fell at the first hurdle. 

Can you explain how to set up a token file or point me at the appropriate documentation which explains how to create it? I am very familiar with creating the tokens, but have not seen that used in this way before, and could not find anything online.

**Comment by tstromberg** [comment]
Sure, I think we can clarify the documentation. Does this help?

# Get token: https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line
# Store token:  `echo YOUR_GENERATED_TOKEN > /path/to/file`

**Comment by RCheesley** [comment]
Thanks that's really helpful, so simple yet I tried searching all over the place to try to find what it actually was looking for (For example what the syntax needed to be etc) and didn't find anything! Happy to make a PR to add it to the readme if you like.
