### ISSUE TITLE
Add mouse-over support & documentation for tags

### ISSUE THREAD

**Issue by medyagh** [google/triage-party#54]
for example I wanna know what does send mean, I would like to hover over it and tell me in a hint that means...
<img width="150" alt="Screen Shot 2020-05-04 at 2 51 34 PM" src="https://user-images.githubusercontent.com/4564227/81017235-d8721000-8e16-11ea-830c-2b4f9ebf3863.png">

is there a place we could see the definition of them?

**Comment by tstromberg** [comment]
https://github.com/google/triage-party#filter-language has rudimentary documentation. Tags are worthy of it's own docs section, however.

**Comment by tstromberg** [comment]
Improved documentation: https://github.com/google/triage-party/blob/master/docs/config.md#tags
